# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties (https://fabricmc.net/versions.html)
minecraft_version=26.3
loader_version=0.18.4

# Mod Properties (to automatically tag on linux: 'git tag $(grep -oP '^mod_version = \K.*' gradle.properties)')
mod_version = 1.4.7+mc-26.3
maven_group = net.clayborn
archives_base_name = AccurateBlockPlacement-Reborn

# Dependencies
fabric_api_version=0.160.5+26.3
mod_menu_version=21.0.0-beta.1
cloth_config_version=26.3.158